### ISSUE TITLE
discussion: Open source license

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/VectorChord#123]
Some users have expressed concerns that the AGPL hinders their product adoption.

**Comment by gaocegege** [comment]
After some research, we could have AGPL and Elastic V2 dual licenses, similar to ElasticSearch. 

It means that users could choose from these two licenses and select their preferences

WDYT

**Comment by aaronliu0130** [comment]
Is this AGPLv3 only, or v3-or-later?

**Comment by usamoi** [comment]
> Is this AGPLv3 only, or v3-or-later?

AGPL-3.0-only. If the Free Software Foundation releases a new version of AGPL, we will consider supporting it at that time.
