### ISSUE TITLE
benchmark: benchmark against fp16 implementation

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/VectorChord#143]

**Comment by cutecutecat** [comment]
## Conceptions
`non-fp16` instance: `i4i.xlarge` without `avx512_fp16` instruction
`fp16` instance: `i7ie.xlarge` with `avx512_fp16` instruction set

`disk`: Restart docker image and clean page cache by `sudo echo 3 > sudo /proc/sys/vm/drop_caches`
`mem`: Run a second time to ensure all results have been cached

## Top10 bench for laion-5m

| nprob | epsilon | QPS on non-fp16 | recall on non-fp16 | QPS on fp16 | recall on fp16 |
| ----- | ------- | --------------- | ------------------ | ----------- | -------------- |
| 20    | 1.9     | 343.72          | 0.9454             | 375.12      | 0.9358         |
| 20    | 1.5     | 367.93          | 0.9434             | 459.34      | 0.9339         |
| 20    | 1.0     | 432.48          | 0.9318             | 503.48      | 0.9233         |
| 50    | 1.9     | 199.44          | 0.9728             | 273.95      | 0.9616         |
| 50    | 1.5     | 225.60          | 0.9708             | 301.19      | 0.9600         |
| 50    | 1.0     | 260.27          | 0.9579             | 321.94      | 0.9483         |
| 50    | 0.8     | 273.05          | 0.9455             | 341.62      | 0.9369         |
| 100   | 1.0     | 164.62          | 0.9667             | 211.23      | 0.9507         |
| 100   | 0.8     | 176.30          | 0.9540             | 213.27      | 0.9451         |
| 200   | 0.8     | 99.91           | 0.9581             | 147.84      | 0.9144         |

## Top100 bench for laion-5m

| nprob | epsilon | QPS disk/mem  on non-fp16 | recall on non-fp16 | QPS disk/mem  on fp16 | recall on fp16 |
| ----- | ------- | ------------------------- | ------------------ | --------------------- | -------------- |
| 20    | 1.9     | 113.98 / 252.11           | 0.9173             | 147.84 / 283.80       | 0.9144         |
| 50    | 1.9     | 83.90 / 168.04            | 0.9625             | 105.84 / 188.92       | 0.9582         |
| 50    | 1.5     | 94.01 / 198.50            | 0.9601             | 154.10 / 224.01       | 0.9560         |
| 50    | 1.0     | 99.75 / 232.28            | 0.9474             | 156.61 / 266.03       | 0.9445         |
| 100   | 1.0     | 85.07 / 150.88            | 0.9631             | 138.59 / 177.93       | 0.9597         |
| 100   | 0.8     | 93.32 / 154.57            | 0.9512             | 157.31 / 193.96       | 0.9486         |
| 200   | 0.8     | 64.91 / 92.95             | 0.9585             | 107.63 / 117.77       | 0.9556         |
