### ISSUE TITLE
test: Streaming vector search benchmark

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/VectorChord#37]
Reference: https://github.com/harsha-simhadri/big-ann-benchmarks/tree/main/neurips23/streaming

**Comment by kemingy** [comment]
- test on AWS i4i.large with 2vCPU + 16G RAM + NVME
- dataset: GIST 1M
- max workers: set to vCPU number
- steps
  - insert 700k
  - build index
  - insert 300k
  - query


| Index | Build Index (seconds) | Insert After Build (seconds) | Query QPS/Recall (top10) | Query QPS/Recall (top100) |
|--------|--------|--------|--------|--------|
| HNSW (pgvector) | 3083.87 | 2130.52 | 201.64 / 1 | 164.37 / 0.9571 |
| RaBitQ (vchord) | 2964.83 | 152.82 | 165.89 / 0.9995 | 48.65 / 0.4521 |
