### ISSUE TITLE
research: benchmark on large datasets

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/VectorChord#42]
# Targets
| dataset       | metric | dim  | nlist         |
| ------------- | ------ | ---- | ------------- |
| laion-5m      | dot    | 768  | 8192 / 16384  |
| laion-20m     | dot    | 768  | 16384 / 32786 |
| ms-macro-100m | /      | 768  | 65536         |

## Hardware
i4i.2xlarge = 64 GB / 8 vcpus / 1.8T nvme ssd

**Comment by cutecutecat** [comment]
## Laion-100m single-thread nlist = 160000

```
nlist = 160000
machine = i4i.xlarge -> [vcpu = 4 memory = 32G ssd = 937G]
jit = false
effective_io_concurrency = 200
with prewarm
```

Tuning nprobe and epsilon

| nprob       | epsilon | P50 latency | P99 latency | QPS   | recall | hit rate |
| ----------- | ------- | ----------- | ----------- | ----- | ------ | -------- |
| 50          | 1.9     | 110.60ms    | 1421.78ms   | 5.09  | 0.9544 | 75.51%   |
| 50          | 1.5     | 60.23ms     | 856.74ms    | 8.74  | 0.9521 | 83.73%   |
| 50          | 1.0     | 29.05ms     | 320.58ms    | 17.02 | 0.9421 | 91.22%   |
| 100         | 1.9     | 119.02ms    | 1675.42ms   | 4.51  | 0.9672 | 78.84%   |
| 100         | 1.5     | 77.22ms     | 1042.41ms   | 7.24  | 0.9650 | 85.95%   |
| 100【good】 | 1.0     | 34.78ms     | 363.49ms    | 14.84 | 0.9536 | 92.97%   |
| 100         | 0.5     | 22.59ms     | 148.25ms    | 25.69 | 0.9079 | 96.23%   |
| 200         | 1.0     | 36.99ms     | 456.09ms    | 14.45 | 0.9608 | 95.04%   |
| 200         | 0.75    | 29.97ms     | 260.68ms    | 18.91 | 0.9461 | 96.43%   |
| 400【best】 | 0.8     | 37.10ms     | 302.29ms    | 16.18 | 0.9535 | 97.63%   |
| 400         | 0.75    | 35.16ms     | 269.50ms    | 17.13 | 0.9497 | 97.78%   |

## Laion-100m multi-thread nlist = 160000

| nprob / epsilon | worker | P50 latency | P99 latency | QPS    |
| --------------- | ------ | ----------- | ----------- | ------ |
| 100 / 1.0       | 1      | 34.78ms     | 363.49ms    | 14.84  |
| 100 / 1.0       | 2      | 32.72ms     | 483.60ms    | 30.14  |
| 100 / 1.0       | 4      | 34.06ms     | 482.65ms    | 58.08  |
| 100 / 1.0       | 8      | 38.59ms     | 693.42ms    | 91.44  |
| 100 / 1.0       | 16     | 62.22ms     | 762.16ms    | 131.84 |
| 400 / 0.8       | 1      | 37.10ms     | 302.29ms    | 16.18  |
| 400 / 0.8       | 2      | 38.47ms     | 304.45ms    | 31.64  |
| 400 / 0.8       | 4      | 42.81ms     | 327.29ms    | 58.80  |
| 400 / 0.8       | 8      | 54.52ms     | 599.55ms    | 82.48  |
| 400 / 0.8       | 16     | 119.76ms    | 695.45ms    | 98.08  |

**Comment by cutecutecat** [comment]
## Laion-100m single-thread nlist = 160000 Top = 100

```
machine = i4i.xlarge -> [vcpu = 4 memory = 32G ssd = 937G]
nlist = 160000
shared buffer = 28G
jit = false
effective_io_concurrency = 200
with prewarm
```

Tuning nprobe and epsilon

| nprob       | epsilon | P50 latency | P99 latency | QPS  | recall |
| ----------- | ------- | ----------- | ----------- | ---- | ------ |
| 100         | 1.0     | 200.59ms    | 1020.20ms   | 3.95 | 0.9501 |
| 200【best】 | 0.8     | 193.42ms    | 885.59ms    | 4.26 | 0.9502 |
| 400         | 0.8     | 216.46ms    | 1006.84ms   | 3.78 | 0.9563 |
| 400         | 0.7     | 190.63ms    | 847.97ms    | 4.26 | 0.9473 |
| 400         | 0.5     | 151.50ms    | 627.86ms    | 5.41 | 0.9231 |

## Laion-100m multi-thread nlist = 160000 Top = 100

| nprob / epsilon | worker | P50 latency | P99 latency | QPS   |
| --------------- | ------ | ----------- | ----------- | ----- |
| 200 / 0.8       | 1      | 193.42ms    | 885.59ms    | 4.26  |
| 200 / 0.8       | 2      | 168.95ms    | 867.34ms    | 9.24  |
| 200 / 0.8       | 4      | 157.02ms    | 986.21ms    | 18.47 |
| 200 / 0.8       | 8      | 167.84ms    | 1059.32ms   | 34.07 |
| 200 / 0.8       | 16     | OOM         | OOM         | OOM   |

**Comment by cutecutecat** [comment]
## Laion-100m build status
```
machine = i4i.xlarge -> [vcpu = 4 memory = 32G ssd = 937G]
worker = 4
```

CPU consume: 4 x 100%
IO write: 100-200MB/s

```
> iostat
Device            r/s     rkB/s   rrqm/s  %rrqm r_await rareq-sz     w/s     wkB/s   wrqm/s  %wrqm w_await wareq-sz     d/s     dkB/s   drqm/s  %drqm d_await dareq-sz     f/s f_await  aqu-sz  %util
nvme1n1        151.74   5607.25     0.00   0.00    0.17    36.95 5059.84  89094.15     0.18   0.00    0.22    17.61    0.00   9885.48     0.00   0.00    6.17 2093910.90    0.00    0.00    1.16   7.54
```

**Comment by cutecutecat** [comment]
# Cost comparison of databases

| database              | monthly cost on 100m | monthly cost on 5m | 5m scaled to 100m(x20) | vectors per $1 |
| --------------------- | -------------------- | ------------------ | ---------------------- | -------------- |
| VectorChord           | $247                 | /                  | /                      | 404,858        |
| Myscale(Cap)          | $1088                | /                  | /                      | 91,911         |
| Myscale(Std)          | $3840                | /                  | /                      | 26,041         |
| Qdrant                | $4374                | /                  | /                      | 22,867         |
| Zillis Cloud(Cap)     | $2305                | /                  | /                      | 43,383         |
| Zillis Cloud(Perf)    | $7800                | /                  | /                      | 12,820         |
| Pinecone(Cap)         | /                    | $80                | $1600                  | 62,500         |
| Pinecone(Perf)        | /                    | $600               | $12000                 | 8,333          |
| PGVector / PGVecto.rs | /                    | $329               | $6580                  | 15,197         |
| Weaviate              | /                    | $365               | $7300                  | 13,698         |
| Elastic Cloud         | /                    | $983               | $19660                 | 5,086          |

**Comment by cutecutecat** [comment]
# Cost comparison of databases

| database              | monthly cost on 100m | monthly cost on 5m | 5m scaled to 100m(x20) | vectors per $1 |
| --------------------- | -------------------- | ------------------ | ---------------------- | -------------- |
| VectorChord           | $247                 | /                  | /                      | 404,858        |
| Myscale(Cap)          | $1088                | /                  | /                      | 91,911         |
| Myscale(Std)          | $3840                | /                  | /                      | 26,041         |
| Qdrant                | $4374                | /                  | /                      | 22,867         |
| Zillis Cloud(Cap)     | $2305                | /                  | /                      | 43,383         |
| Zillis Cloud(Perf)    | $7800                | /                  | /                      | 12,820         |
| Pinecone(Cap)         | /                    | $80                | $1600                  | 62,500         |
| Pinecone(Perf)        | /                    | $600               | $12000                 | 8,333          |
| PGVector / PGVecto.rs | /                    | $329               | $6580                  | 15,197         |
| Weaviate              | /                    | $365               | $7300                  | 13,698         |
| Elastic Cloud         | /                    | $983               | $19660                 | 5,086          |

**Comment by cutecutecat** [comment]
# Memory based index at memory optimized instance
```
machine = r6a.xlarge -> [vcpu = 4 memory = 32G ebs=200G]
nlist = 8192
shared buffer = 28G
jit = false
effective_io_concurrency = 200
without prewarm but run twice
```

## Laion-5m single-thread nlist = 8192 Top = 10

| nprob | epsilon | P50 latency | P99 latency | QPS    | recall |
| ----- | ------- | ----------- | ----------- | ------ | ------ |
| 50    | 1.9     | 2.62ms      | 5.49ms      | 361.90 | 0.9734 |
| 50    | 1.5     | 2.58ms      | 5.42ms      | 367.35 | 0.9712 |
| 100   | 1.9     | 4.51ms      | 9.41ms      | 209.87 | 0.9826 |
| 100   | 1.5     | 4.12ms      | 7.34ms      | 234.32 | 0.9804 |
| 100   | 1.0     | 3.87ms      | 5.87ms      | 252.48 | 0.9672 |
| 100   | 0.8     | 3.71ms      | 5.47ms      | 264.10 | 0.9544 |
| 100   | 0.6     | 3.70ms      | 5.20ms      | 265.70 | 0.9339 |
| 200   | 1.5     | 7.23ms      | 10.93ms     | 135.56 | 0.9847 |
| 200   | 1.0     | 6.85ms      | 9.35ms      | 144.24 | 0.9713 |
| 200   | 0.8     | 6.70ms      | 8.98ms      | 147.57 | 0.9585 |
| 300   | 1.9     | 10.83ms     | 16.91ms     | 90.38  | 0.9883 |
| 300   | 1.5     | 10.09ms     | 14.05ms     | 97.73  | 0.9861 |
| 300   | 1.0     | 9.78ms      | 12.78ms     | 101.43 | 0.9727 |
| 300   | 0.8     | 9.61ms      | 12.88ms     | 103.21 | 0.9598 |

### multi-thread

| nprob / epsilon | worker | P50 latency | P99 latency | QPS    |
| --------------- | ------ | ----------- | ----------- | ------ |
| 100 / 0.8       | 1      | 3.71ms      | 5.47ms      | 264.10 |
| 100 / 0.8       | 2      | 3.82ms      | 6.03ms      | 509.82 |
| 100 / 0.8       | 4      | 5.18ms      | 8.60ms      | 750.85 |
| 100 / 0.8       | 8      | 10.41ms     | 24.07ms     | 732.73 |
| 100 / 0.8       | 16     | 21.10ms     | 50.14ms     | 724.34 |
| 100 / 0.8       | 32     | 45.22ms     | 100.55ms    | 677.74 |

## Laion-5m single-thread nlist = 8192 Top = 100

| nprob | epsilon | P50 latency | P99 latency | QPS    | recall |
| ----- | ------- | ----------- | ----------- | ------ | ------ |
| 50    | 1.9     | 5.17ms      | 13.34ms     | 174.95 | 0.9627 |
| 50    | 1.5     | 4.35ms      | 10.12ms     | 211.63 | 0.9603 |
| 100   | 1.9     | 7.05ms      | 17.92ms     | 128.63 | 0.9793 |
| 100   | 1.5     | 6.06ms      | 13.22ms     | 153.00 | 0.9767 |
| 100   | 1.0     | 5.26ms      | 9.33ms      | 181.84 | 0.9632 |
| 100   | 0.8     | 5.02ms      | 8.16ms      | 193.06 | 0.9513 |
| 100   | 0.6     | 4.85ms      | 7.36ms      | 201.09 | 0.9332 |
| 200   | 1.5     | 9.28ms      | 18.15ms     | 101.88 | 0.9847 |
| 200   | 1.0     | 8.35ms      | 13.17ms     | 116.47 | 0.9708 |
| 200   | 0.8     | 7.90ms      | 11.58ms     | 124.13 | 0.9586 |
| 300   | 1.9     | 13.60ms     | 29.04ms     | 68.60  | 0.9898 |
| 300   | 1.5     | 12.41ms     | 22.26ms     | 77.28  | 0.9871 |
| 300   | 1.0     | 11.31ms     | 16.50ms     | 86.69  | 0.9731 |
| 300   | 0.8     | 11.06ms     | 15.48ms     | 89.04  | 0.9607 |

### multi-thread

| nprob / epsilon | worker | P50 latency | P99 latency | QPS    |
| --------------- | ------ | ----------- | ----------- | ------ |
| 100 / 0.8       | 1      | 5.02ms      | 8.16ms      | 193.06 |
| 100 / 0.8       | 2      | 5.13ms      | 9.06ms      | 374.05 |
| 100 / 0.8       | 4      | 6.94ms      | 13.50ms     | 549.02 |
| 100 / 0.8       | 8      | 14.61ms     | 36.30ms     | 519.71 |
| 100 / 0.8       | 16     | 32.26ms     | 77.63ms     | 471.70 |
| 100 / 0.8       | 32     | 69.12ms     | 173.03ms    | 434.99 |

**Comment by gaocegege** [comment]
https://github.com/tensorchord/VectorChord/issues/37#issuecomment-2477840444 Streaming vector search benchmark
